stuart:
    extends:
        file: ./minion.yml
        service: minion
    ports:
        - "3000:3000"
    environment:
        - GREETER_NAME=Stuart the Minion

bob:
    extends:
        service: minion
    ports:
        - "3001:3000"
    environment:
        - GREETER_NAME=Bob the Minion

kevin:
    extends:
        service: minion
    ports:
        - "3002:3000"
    environment:
        - GREETER_NAME=Kevin the Minion

kibana:
    image: devdb/kibana
    ports:
        - "5602:5601"
        - "9201:9200"
    exports: 
        - "9200"
    volumes:
        - "/tmp/kibana:/opt/elasticsearch/data"